/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        StandardCalculator calc = new StandardCalculator();
        calc.multiply(Double.MAX_VALUE,Double.MIN_VALUE);
        System.out.println(calc.getResult());
    }
}
