/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Assertions;

import org.junit.jupiter.api.BeforeEach;

import org.junit.jupiter.api.DisplayName;

import org.junit.jupiter.api.Test;

import java.beans.Transient;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
class AppTest{

    private StandardCalculator standardCalculator;

    @BeforeEach
    void setup(){
        standardCalculator = new StandardCalculator();
    }

    //Addition test cases
    @Test
    @DisplayName("Test addition")
    void testAddition(){
        standardCalculator.add(1,1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(2, result);
    }
    @Test
    @DisplayName("Test addition with edge case both 0")
    void testAdditionEdgeCase(){
        standardCalculator.add(0,0);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test addition with edge case both negative")
    void testAdditionEdgeCase2(){
        standardCalculator.add(-1,-1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-2, result);
    }

    @Test
    @DisplayName("Test addition with edge case one positive, one negative")
    void testAdditionEdgeCase3(){
        standardCalculator.add(-1,1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test addition with edge case one negative, one positive")
    void testAdditionEdgeCase4(){
        standardCalculator.add(1,-1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    //Subtraction test cases
    @Test
    @DisplayName("Test subtraction")
    void testSubtraction(){
        standardCalculator.subtract(1,1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test subtraction with edge case both 0")
    void testSubtractionEdgeCase(){
        standardCalculator.subtract(0,0);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test subtraction with edge case both negative")
    void testSubtractionEdgeCase2(){
        standardCalculator.subtract(-1,-1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test subtraction with edge case one negative, one positive")
    void testSubtractionEdgeCase3(){
        standardCalculator.subtract(-1,1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-2, result);
    }

    @Test
    @DisplayName("Test subtraction with edge case one positive, one negative")
    void testSubtractionEdgeCase4(){
        standardCalculator.subtract(1,-1);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(2, result);
    }

    //Multiplication test cases
    @Test
    @DisplayName("Test multiplication")
    void testMultiplication(){
        standardCalculator.multiply(2,3);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(6, result);
    }

    @Test
    @DisplayName("Test multiplication with edge case both 0")
    void testMultiplicationEdgeCase(){
        standardCalculator.multiply(0,0);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    @Test
    @DisplayName("Test multiplication with edge case both negative")
    void testMultiplicationEdgeCase2(){
        standardCalculator.multiply(-2,-3);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(6, result);
    }

    @Test
    @DisplayName("Test multiplication with edge case one negative, one positive")
    void testMultiplicationEdgeCase3(){
        standardCalculator.multiply(-3,4);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-12, result);
    }

    @Test
    @DisplayName("Test multiplication with edge case one positive, one negative")
    void testMultiplicationEdgeCase4(){
        standardCalculator.multiply(2,-5);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-10, result);
    }

    //Division test cases
    @Test
    @DisplayName("Test division")
    void testDivision(){
        standardCalculator.divide(6,3);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(2, result);
    }

    @Test
    @DisplayName("Test division with edge case both 0")
    void testDivisionEdgeCase(){
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            standardCalculator.divide(0,0);
        });
    }
     @Test
     @DisplayName("Test division with edge case both negative")
     void testDivisionEdgeCase2(){
         standardCalculator.divide(-6,-3);
         int result = standardCalculator.getResult();
         Assertions.assertEquals(2, result);
     }

    @Test
    @DisplayName("Test division with edge case one negative, one positive")
    void testDivisionEdgeCase3(){
        standardCalculator.divide(-6,3);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-2, result);
    }

    @Test
    @DisplayName("Test division with edge case one positive, one negative")
    void testDivisionEdgeCase4(){
        standardCalculator.divide(6,-3);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(-2, result);
    }

    @Test
    @DisplayName("Test division by zero")
    void testDivisionByZero(){
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            standardCalculator.divide(6,0);
        });
    }

    @Test
    @DisplayName("Test division by smaller numerator")
    void testDivisionBySmallerNumerator(){
        standardCalculator.divide(3,6);
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }

    //Test clear result
    @Test
    @DisplayName("Test clear result")
    void testClearResult(){
        standardCalculator.add(5,5);
        standardCalculator.clearResult();
        int result = standardCalculator.getResult();
        Assertions.assertEquals(0, result);
    }
}
